[package]
name = "itest-dependency"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license = "MPL-2.0"
publish = false

[dependencies]
godot = { path = "../../godot", default-features = false }
