[package]
name = "godot-fmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "gdext_bench"
harness = false
